<?php

return array(
    "1" => "Calle",
    "2" => "Paseo",
    "3" => "Avenida",
    "4" => "Ronda",
    "5" => "Travesía",
    "6" => "Carretera",
    "7" => "Rambla",
    "8" => "Plaza",
    "9" => "Pasaje",
    "10" => "Bajada",
    "11" => "Vía",
    "13" => "Urbanización",
    "14" => "Camino",
    "15" => "Sector",
    "16" => "Glorieta",
    "17" => "Alameda",
    "18" => "Barranco",
    "19" => "Calleja",
    "20" => "Cuesta",
    "21" => "Grupo",
    "22" => "Gran via",
    "23" => "Jardines",
    "24" => "Muelle",
    "25" => "Poligono industrial",
    "26" => "Parque",
    "27" => "Prolongación",
    "28" => "Riera",
    "29" => "Rua",
    "30" => "Subida",
);
