<?php

return array(
    "1" => array(
        "1" => __("Semisótano", 1),
        "2" => __("Triplex", 1),
        "3" => __("Dúplex", 1),
        "4" => __("Buhardilla", 1),
        "5" => __("Ático", 1),
        "6" => __("Estudio", 1),
        "7" => __("Loft", 1),
        "8" => __("Otro", 1),
        "9" => __("Piso", 1),
        "10" => __("Apartamento", 1),
        "11" => __("Planta baja", 1),
    ),
    "2" => array(
        "13"	=> __("Casa", 1),
        "14"	=> __("Cortijo", 1),
        "17"	=> __("Adosada", 1),
        "18"	=> __("Caserio", 1),
        "19"	=> __("Pareada", 1),
        "20"	=> __("Chalet/Torre", 1),
        "21"	=> __("Masía", 1),
        "23"	=> __("Unifamiliar", 1),
        "24"	=> __("Casa rústica", 1),
        "25"	=> __("Casa de pueblo", 1),
        "26"	=> __("Casa rural", 1),
        "27"	=> __("Bungalow", 1),
        "28"	=> __("Casona", 1),
    ),
    "3" => array(
        "30" => __("En mercado público", 1),
        "31" => __("1ª línea comercial", 1),
        "32" => __("Gran almacén", 1),
        "33" => __("3ª línea comercial", 1),
        "34" => __("Enclave estratégico", 1),
        "35" => __("2ª línea comercial", 1),
        "36" => __("1ª línea de lujo", 1),
        "37" => __("Almacén", 1),
        "38" => __("Sótano", 1),
        "39" => __("En gran superficie especializada", 1),
        "40" => __("Factory outlet", 1),
        "41" => __("En espacios comerciales", 1),
        "42" => __("Comercio de barrio", 1),
        "43" => __("En centro comercial", 1),
        "88" => __("Oficina", 1),
        "89" => __("Polígono Industrial", 1),
    ),
    "4" => array(
        "44" => __("Otro", 1),
        "45" => __("Media representatividad", 1),
        "46" => __("Alta representatividad", 1),
        "47" => __("Baja representatividad", 1),
        "85" => __("Centro de negocios", 1),
        "86" => __("Piso", 1),
    ),
    "5" => array(
        "48" => __("Residencial", 1),
        "49" => __("Industrial", 1),
        "50" => __("Mixto", 1),
        "51" => __("Oficinas", 1),
    ),
    "6" => array(
        "52" => __("Ganadero", 1),
        "53" => __("Otros", 1),
        "54" => __("Urbanizable", 1),
        "55" => __("Equipamientos", 1),
        "56" => __("Residencial", 1),
        "57" => __("Comercial", 1),
        "58" => __("Parcelable", 1),
        "59" => __("Agrícola", 1),
        "60" => __("Industrial", 1),
        "90" => __("Terciario", 1),
    ),
    "7" => array(
        "61" => __("Nave comercial", 1),
        "62" => __("Polígono urbanizado", 1),
        "63" => __("Polígono semiurbanizado", 1),
        "64" => __("Nave industrial", 1),
        "65" => __("Polígono no urbanizado", 1),
    ),
    "8" => array(
        "66" => __("Negocio", 1),
        "67" => __("Otros", 1),
        "68" => __("Moto", 1),
        "69" => __("Doble", 1),
        "70" => __("Individual", 1),
    ),
    "10" => array(
        "72" => __("Residencia 3ª Edad", 1),
        "73" => __("Apart Hotel", 1),
        "75" => __("Hotel", 1),
        "78" => __("Turismo Rural", 1),
    ),
    "12" => __("Trastero", 1),
);
