<?php

return array(
    "1" => "SMS en cambio precio",
    "2" => "Prensa",
    "3" => "Tasación",
    "4" => "e-mail",
    "5" => "Reservar Inmueble",
    "6" => "Oferta económica",
    "7" => "Publicar en prensa",
    "8" => "Internet",
    "9" => "Llamada Cliente",
    "10" => "Llamada Propietario",
    "11" => "Contrato",
    "12" => "Email en cambio de precio",
    "13" => "Primera visita",
    "14" => "Colgar Cartel",
    "15" => "Seguimiento de captación",
    "16" => "Alerta en cambio de precio",
    "17" => "Enviar SMS",
    "18" => "SMS en cruce",
    "19" => "Publicar en Díptico",
    "20" => "Telemarketing",
    "21" => "Enviar e-mail",
    "22" => "Segunda visita",
    "23" => "Visita",
    "24" => "Visita captación",
    "25" => "Seguimiento",
    "26" => "Email en cruce",
    "27" => "Mailing",
    "28" => "Escaparate",
    "29" => "Alerta en cruce",
    "31" => "Reunión Cliente",
    "33" => "Revista",
    "34" => "Solicitud de información",
    "35" => "Atención telefónica",
    "36" => "Atención oficina",
    "37" => "Acción comercial propia",
);
