<?php
if ($lang_adm == 'es') {
    return array(
        "featuresPool" => __("Piscina", 1),
        "featuresStudio" => __("Estudio", 1),
        "featuresWardrobes" => __("Armarios", 1),
        "featuresConditionedAir" => __("Aire acondicionado", 1),
        "featuresGarden" => __("Jardín", 1),
        "featuresTerrace" => __("Terraza", 1),
        "featuresBalcony" => __("Balcón", 1),
        "featuresStorage" => __("Almacenamiento", 1),
        // "featuresHeating" => __("Calefacción", 1),
        "featuresEquippedKitchen" => __("Cocina equipada", 1),
        "featuresEquippedWithFurniture" => __("Amueblado", 1),
        "featuresParkingAvailable" => __("Parking disponible", 1),
        "featuresParkingAutomaticDoor" => __("Puerta automática de Parking", 1),
        "featuresParkingPlaceCovered" => __("Aparcamiento cubierto", 1),
        "featuresPenthouse" => __("Ático", 1),
        "featuresSecurityAlarm" => __("Alarma", 1),
        "featuresAccessControl" => __("Control de acceso", 1),
        "featuresAllowPets" => __("Se permiten mascotas", 1),
        "featuresBathroomInside" => __("Baño Interior", 1),
        "featuresBathroomAdapted" => __("Baño adaptado", 1),
        "featuresBuildingAdapted" => __("Edificio adaptado", 1),
        "featuresHandicapAdaptedAccess" => __("Acceso adaptado para discapacitados", 1),
        "featuresChimney" => __("Chimenea", 1),
        "featuresDuplex" => __("Duplex", 1),
        "featuresEmergencyExit" => __("Salida de emergencia", 1),
        "featuresEmergencyLights" => __("Luces de emergencia", 1),
        "featuresExtinguishers" => __("Extintores", 1),
        "featuresHotWater" => __("Agua caliente", 1),
        "featuresLocatedAtCorner" => __("Esquina", 1),
        "featuresSecurityDoor" => __("Puerta de seguridad", 1),
        "featuresFireDetectors" => __("Detectores de incendios", 1),
        "featuresFireDoors" => __("Puertas anti fuego", 1),
        "featuresLiftAvailable" => __("Ascensor", 1),
        "featuresOfficeBuilding" => __("Edificio de oficinas", 1),
        "featuresSecurity24h" => __("Servicio de seguridad las 24 horas", 1),
        "featuresSecuritySystem" => __("Sistema de seguridad", 1),
        "featuresSmokeExtraction" => __("Extracción de humo", 1),
        "featuresSprinklers" => __("Aspersores", 1),
        "featuresSuspendedCeiling" => __("Techo suspendido", 1),
        "featuresUtilitiesElectricity" => __("Disponibilidad de electricidad.", 1),
        "featuresUtilitiesNaturalGas" => __("Disponibilidad de Gas natural.", 1),
    );
} else {
    return array(
        "featuresPool" => __("Pool", 1),
        "featuresStudio" => __("Studio", 1),
        "featuresWardrobes" => __("Wardrobes", 1),
        "featuresConditionedAir" => __("Conditioned Air", 1),
        "featuresGarden" => __("Garden", 1),
        "featuresTerrace" => __("Terrace", 1),
        "featuresBalcony" => __("Balcony", 1),
        "featuresStorage" => __("Storage", 1),
        // "featuresHeating" => __("Heating", 1),
        "featuresEquippedKitchen" => __("Equipped Kitchen", 1),
        "featuresEquippedWithFurniture" => __("Equipped With Furniture", 1),
        "featuresParkingAvailable" => __("Parking Available", 1),
        "featuresParkingAutomaticDoor" => __("Parking Automatic Door", 1),
        "featuresParkingPlaceCovered" => __("Parking Place Covered", 1),
        "featuresPenthouse" => __("Penthouse", 1),
        "featuresSecurityAlarm" => __("Security Alarm", 1),
        "featuresAccessControl" => __("Access Control", 1),
        "featuresAllowPets" => __("Bathroom inside", 1),
        "featuresBathroomInside" => __("Baño Interior", 1),
        "featuresBathroomAdapted" => __("Bathroom Adapted", 1),
        "featuresBuildingAdapted" => __("Building Adapted", 1),
        "featuresHandicapAdaptedAccess" => __("Handicap adapted access", 1),
        "featuresChimney" => __("Chimney", 1),
        "featuresDuplex" => __("Duplex", 1),
        "featuresEmergencyExit" => __("Emergency Exit", 1),
        "featuresEmergencyLights" => __("Emergency Lights", 1),
        "featuresExtinguishers" => __("Extinguishers", 1),
        "featuresHotWater" => __("Hot Water", 1),
        "featuresLocatedAtCorner" => __("Located At Corner", 1),
        "featuresSecurityDoor" => __("Security Door", 1),
        "featuresFireDetectors" => __("Fire detectors", 1),
        "featuresFireDoors" => __("Fire doors", 1),
        "featuresLiftAvailable" => __("Lift", 1),
        "featuresOfficeBuilding" => __("Office building", 1),
        "featuresSecurity24h" => __("24 hr security service", 1),
        "featuresSecuritySystem" => __("Security system", 1),
        "featuresSmokeExtraction" => __("Smoke extraction", 1),
        "featuresSprinklers" => __("Sprinklers", 1),
        "featuresSuspendedCeiling" => __("Suspending ceiling", 1),
        "featuresUtilitiesElectricity" => __("Electricity availability", 1),
        "featuresUtilitiesNaturalGas" => __("Natural Gas availability", 1),
    );
}

